### ISSUE TITLE
Ashita Windower Superwarp shim

### ISSUE THREAD

**Issue by Tru14** [baharms/superwarp#1]
Would you or anyone be willing to make a shim for Ashita? This would be groundbreaking for multiboxing on Ashita. Thank you!

**Comment by Tru14** [comment]
Or even convert this to a full Ashita addon! I would be incredibly grateful!

**Comment by baharms** [comment]
Alas, I don't use Ashita, and probably never will. Eventually I will have to update this to Windower 5 though.
