### ISSUE TITLE
Teleport on Follow

### ISSUE THREAD

**Issue by bjggi** [baharms/superwarp#10]
First, thanks for your work. Beta is looking great!

I have a question, is there a pattern which character is getting teleported first?

Would be great if somehow this could be steered (per settings maybe, or whoever starts the input is ported last), so when u have multiple characters on follow and ur main is getting ported, they dont wander off :)

Best regards

**Comment by baharms** [comment]
The pattern is alphabetical. It's really the only way to guarantee that there's a consistent order on every client. As soon as the command is entered, all additional local clients receive the message simultaneously, but they each calculate their delay based on alphabetical order in the party. Technically, if all the local clients aren't in the same party, they could get stuck.

**Comment by bjggi** [comment]
Ah i see, that's too bad, the name of my main is the first in alphabetical order :/ Thx for ur answer.

**Comment by baharms** [comment]
I know it's not in the description for this issue, but I just added the ability to send a windower command before and after a warp (to pause a 3rd-party addon that follows for example). Additionally, by default superwarp will cancel /follow and autorun.
I'm still thinking about something that might help with ordering local instances and warping.

**Comment by bjggi** [comment]
Oh great, i use [FastFollow](https://github.com/DiscipleOfEris/FastFollow). Now with <command_before_warp>ffo stopall</command_before_warp> it stops all.

command_on_arrival not gonna work, since "ffo me" will be sent to all chars.

**Comment by baharms** [comment]
If you always have follow on one character, you can set character-based settings in the file for him. 
I'd set each other characters to just do "ffo stop" in case they stop outside the 6 yalms that you can warp within. 

Or, you can fork fastfollow and add a pause command :P

**Comment by bjggi** [comment]
simulate_client_lock works great with FF, thx :)
