### ISSUE TITLE
Suggestion - Warp Ring

### ISSUE THREAD

**Issue by bjggi** [baharms/superwarp#3]
First, thank you for this great Addon.

I would like to make a suggesion, would it be possible to add the "Warp Ring" to your Addon. Something like "//wr all", and the Ring will be used on all Chars. 

There is an Addon who kinda does that: https://github.com/from20020516/MyHome but it is very buggy, specially when used on multible chars.

Thanks!

**Comment by baharms** [comment]
Equipping items is out of scope for this addon. Though I appreciate the suggestion. Like you said, there's at least one other addon that works. And many people just roll it into their gearswap.
