### ISSUE TITLE
Suggestion for new features #2

### ISSUE THREAD

**Issue by Chevalier501** [baharms/superwarp#4]
I love this addon. It's a such a quality of life improvement 6 boxing :). I find myself using it over using the menus even when I'm playing with one character.  I wondered if it was possible to add Proto-Waypoints as well? I'm not sure but I think there was an addon once that had something like that. I can't seem to find it.  Regardless, it would be nicer if it could be part of the package :) 

That and maybe entering things like old dyna or (HT)BCNM, but I guess that would be tricky with difficulty etc.. 

Keep up the good work! Thank you so much for this addon.

**Comment by baharms** [comment]
I did add proto-waypoints with 0.96. //pwp etc.
I don't think HT BCNMs would work very well with this addon, but thanks for the suggestion.
