### ISSUE TITLE
Fuzzy search for Pashhow incorrectly returns Pashhow [S]

### ISSUE THREAD

**Issue by Nullsloth** [baharms/superwarp#6]
EDIT had old version for altepa went through commits. Trying to sg to normal pashhow takes you to pashhow [S] still tho.

**Comment by baharms** [comment]
I misspelled Pashhow for the present day zone, but not for the shadowreign version. I will test soon.

**Comment by baharms** [comment]
Fixed in beta branch. When it's pushed to trunk, it'll be fixed there too :D.
