### ISSUE TITLE
Question/Feature Suggestion mapping

### ISSUE THREAD

**Issue by Noobcakes** [baharms/superwarp#7]
Is it possible to map zones? And if not, could it be? I know you can create aliases for the homepoint numbers in each zone and the fuzzy logic is impressive with zone names, but it would be super cool if I could map zone names for the ones that aren't picked up so easily. 

For example, 'w ado' takes me to western adoulin, but 'e ado' doesn't work. Is there a way to create aliases for things like 'e ado' (and whatever other zone's tend to be tedious to type out) so I can be even lazier than I already am?

**Comment by baharms** [comment]
I have added this feature to the beta branch. Thanks for the suggestion!

**Comment by Noobcakes** [comment]
That's amazing. This add on is a huge convenience and now it's that much better.  Thank you so much.
