### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by ivaanant** [baharms/superwarp#8]
Hello,
not sure why but i cant get superwarp to work.
 
i have the superwarp.lua file saved pathed as such in folder:
Windower > addons > superwarp > superwarp.lua

when i try to load it in game "//lua load superwarp" or "//lua load superwarp.lua" i get 
"No File 'C:/Program Files (x86) FFXT WINDOWER//plugins/libs/map/maps.dll'" or just file does not exist.

Any thoughts on what i did wrong? 

thanks for any help!

**Comment by Jinx-v7** [comment]
I'm having the same issue.. any luck figuring out what was happening?

**Comment by baharms** [comment]
Sounds like you don't have the whole folder. You need to have superwarp.lua, and the maps folder with abyssea, escha, guides, homepoints, maps, unity, and waypoints.lua in there. The maps folder holds all the warp data.

**Comment by Noelurena** [comment]
I'm having same issue also, and I have everything from maps and saved as it is posted. and when I run it I still get the issue of file not found on extension .dll and .lua can you please post a step by step on how to do this please?
