### ISSUE TITLE
Occasionally doesn't warp all characters

### ISSUE THREAD

**Issue by Noobcakes** [baharms/superwarp#9]
When using the 'all' command, occasionally one of the characters will give the message 'warping to wherever...' , but will remain in the same place. It seems to be random. sometimes it's the character that entered the '//... all ...' command, sometimes a different character. Only happens on beta afaik.

**Comment by Chevalier501** [comment]
I've been having the same issue too, but I've been having it with the Myhome addon too. Might be some other thing that's broken. Send?

**Comment by Noobcakes** [comment]
AFIK super warp uses ipc. Don't think it relies on any other addons.

**Comment by baharms** [comment]
This should be fixed with v0.96. Sometimes a "poke" of an npc was being lost. But now it should retry.
